In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [11]:
f = lambda x: 2**x/x
n2 = np.arange(1, 21)
a = f(n2)
a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [14]:
f = lambda x: (0.1**(3*x))*0.2**(4*x)
a = np.arange(6)
sum(f(a))


1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [26]:
M = np.zeros((8,8), dtype=int)
M[1::2,::2] = 1
M[::2,1::2] = 1
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [34]:
X = np.random.random((5, 2))
Y,Z = X[:,0], X[:,1]
ro = np.hypot(Y, Z)
fi = np.arctan2(Z,Y)
print(ro)
print(fi)

[0.22284744 0.86824921 0.61883606 0.76209604 0.98175311]
[0.32408424 0.25325864 0.27611272 1.36258019 0.38262117]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [41]:
X = np.random.random((10, 10))
x = np.unravel_index(np.argmax(X, axis=None), X.shape)
print(X)
x
## your code

[[0.27120407 0.05996513 0.80064906 0.0444606  0.7210773  0.2163938
  0.54722481 0.17541013 0.61653615 0.82416069]
 [0.30831517 0.45208548 0.26387503 0.63145131 0.51624198 0.52937066
  0.2666941  0.77024576 0.16470426 0.03043898]
 [0.21616798 0.85098479 0.6939424  0.40226453 0.48885987 0.35001838
  0.49606675 0.52386834 0.49187235 0.88378321]
 [0.16799886 0.98209854 0.70829564 0.18704804 0.55155095 0.39712855
  0.983837   0.40778794 0.65059232 0.97352825]
 [0.04591104 0.20529346 0.53200086 0.83635489 0.92596308 0.52891743
  0.06703322 0.36616068 0.21796937 0.00486937]
 [0.6445027  0.59120288 0.77822026 0.77299611 0.88611686 0.86605132
  0.69038265 0.74289197 0.83302808 0.68109407]
 [0.67732024 0.32785736 0.35171928 0.19920125 0.81205587 0.44490409
  0.45722777 0.00578023 0.56996416 0.30751678]
 [0.2925851  0.76736569 0.99143751 0.16010648 0.37211733 0.19965515
  0.23894244 0.66349308 0.64762148 0.53082912]
 [0.29040772 0.47780367 0.85174772 0.78114496 0.07709277 0.33178445
  0.88381327 

(7, 2)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
y_0 = np.ones(10)*y[0, 0]
y_1 = np.ones(10)*y[0, 1]

X_1 = np.abs(X[:, 0] - y_0)
X_2 = np.abs(X[:, 1] - y_1)
nearer = np.sqrt(X_1**2 + X_2**2)
min_dot = X[np.argmin(nearer),:]
print(X, y)
print(X_1)
print(X_2)
print(nearer)
print('nearer dot:', min_dot)
## your code

[[0.01157312 0.15652557]
 [0.79839341 0.62325842]
 [0.16098715 0.16869844]
 [0.10879887 0.56497924]
 [0.38764839 0.94032796]
 [0.53075265 0.48213964]
 [0.53166493 0.92540819]
 [0.33298862 0.7968486 ]
 [0.78545223 0.99565922]
 [0.78332343 0.52069965]] [[0.72344909 0.22592794]]
[0.71187597 0.07494431 0.56246195 0.61465023 0.33580071 0.19269645
 0.19178416 0.39046047 0.06200313 0.05987433]
[0.06940237 0.39733048 0.0572295  0.3390513  0.71440002 0.25621171
 0.69948026 0.57092066 0.76973128 0.29477171]
[0.71525107 0.4043367  0.56536595 0.70196202 0.78938553 0.32058752
 0.72529566 0.69167173 0.77222447 0.30079112]
nearer dot: [0.78332343 0.52069965]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [65]:
## your code
x1 = np.linspace(-3, 0, 100)
x2 = np.linspace(0.1, 2, 100)
x3 = np.linspace(2.1, 3, 100)

(x1**2+2*x1+6).tolist() + (x2+6).tolist() + (x3**2+4*x3-4).tolist()

[9.0,
 8.879706152433425,
 8.761248852157943,
 8.644628099173554,
 8.529843893480258,
 8.416896235078054,
 8.305785123966942,
 8.196510560146924,
 8.089072543617998,
 7.983471074380166,
 7.879706152433425,
 7.777777777777778,
 7.677685950413223,
 7.579430670339761,
 7.483011937557392,
 7.3884297520661155,
 7.295684113865932,
 7.2047750229568415,
 7.115702479338843,
 7.028466483011938,
 6.943067033976125,
 6.859504132231406,
 6.777777777777777,
 6.697887970615243,
 6.619834710743801,
 6.543617998163453,
 6.469237832874196,
 6.396694214876033,
 6.325987144168962,
 6.257116620752984,
 6.190082644628099,
 6.124885215794307,
 6.061524334251607,
 6.0,
 5.940312213039485,
 5.882460973370065,
 5.8264462809917354,
 5.772268135904499,
 5.719926538108356,
 5.669421487603305,
 5.620752984389348,
 5.573921028466483,
 5.528925619834711,
 5.485766758494032,
 5.444444444444445,
 5.404958677685951,
 5.367309458218549,
 5.331496786042241,
 5.297520661157025,
 5.265381083562902,
 5.235078053259871,
 5.20

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [126]:
X = np.random.random((10, 10))
sr = np.mean(X, axis=1)
a = np.ones((10,10))*sr
a = a.T
X_new = X - a
print(X)
print(a,'sdfgsf')
print(X_new)
sr_new = np.mean(X_new, axis=1)
sr_new
## your code

[[0.42456752 0.33043541 0.75750784 0.46449267 0.2935126  0.71347453
  0.77323743 0.26759876 0.67191621 0.5643516 ]
 [0.53410637 0.35522244 0.99400797 0.31209076 0.25960189 0.89016968
  0.55748926 0.87590793 0.63326626 0.00792691]
 [0.15978935 0.40679183 0.51181596 0.84122925 0.7044155  0.26448216
  0.07021715 0.50985372 0.10874521 0.97448461]
 [0.0564413  0.13759599 0.56882929 0.44082638 0.64120985 0.42918839
  0.57581893 0.89374204 0.42656963 0.41982695]
 [0.85418688 0.92686235 0.22681424 0.84907357 0.48970297 0.93588751
  0.38130711 0.07073196 0.51786578 0.365913  ]
 [0.42904406 0.29643592 0.34491717 0.16836287 0.62124821 0.04842416
  0.20169401 0.5711492  0.76486457 0.07373817]
 [0.95261528 0.98985785 0.05664408 0.2845297  0.09972231 0.36547191
  0.18229894 0.3001155  0.92440198 0.93602748]
 [0.37967096 0.82860242 0.87207572 0.51496754 0.5389999  0.98982335
  0.67606418 0.61686285 0.13542246 0.61671137]
 [0.66931499 0.08036334 0.52309278 0.05340662 0.89451203 0.7498072
  0.80066993 

array([-1.11022302e-16, -4.44089210e-17, -4.44089210e-17,  0.00000000e+00,
       -2.22044605e-17,  4.44089210e-17, -3.33066907e-17,  5.55111512e-17,
        1.11022302e-16,  4.44089210e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [141]:
X = np.random.normal(loc=5, scale=2., size=1000)
vib_sr = np.sum(X)/X.shape[0]
vib_disp = np.sum(np.square(X))/X.shape[0] - vib_sr**2
print(X)
print(vib_sr)
print(vib_disp)

[ 6.79012725  5.34958221  3.12996236  2.92465244  2.08395735  3.59780941
  8.10360151  3.3587101   5.36290804  4.24818051  4.27492956  3.45916153
  5.99085443  4.69372831  4.55281812  7.74508333  4.47067349  6.67260006
  3.3761482   3.86593711  7.11934634  6.47021959  6.12095272  5.97950157
  9.09406017  3.95313313  3.98496393  1.97591809 -0.41913006  5.56538405
  4.98169606  7.69325592  3.79888044  7.0535859   3.50269206  4.81156072
  4.75496662  2.86349528  5.8651527   4.30017721  5.52610902  4.23052632
  6.47785226  1.5539159   5.8263011   6.27473517  6.24774934  5.71983937
  9.19568634  5.32017254  4.36533758  3.45840665  6.08643626  9.05306154
  5.19265842  8.89933547  2.83703809  8.81853657  9.16498078  1.23132243
  2.60396804  6.83039715  4.8140526   6.70295898  2.86252172  6.35629531
  4.91491942  4.95295683  4.64673406  6.15669303 -1.06968176  6.18793893
  4.23283703  5.56022019  7.0869783   4.83462377  4.54965419  8.57394296
  3.71978051  4.5273325   8.06147048  2.85405578  5

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [59]:
## your code
line = [0,1,2,3,4]
matrix = np.zeros((5,5))+line
r = np.arange(5)*(-1)
rows, col = np.ogrid[:5, :5]
r[r < 0] += 5
col = col - r[:,np.newaxis]
print(matrix[rows, col])

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]
 [4. 0. 1. 2. 3.]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [116]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        print(val)
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

69.82840645775238
<class 'list'>
33.03082835669241
<class 'list'>
77.69198397984533
<class 'list'>
31.196320379402795
<class 'list'>
73.83748367354691
<class 'list'>


[4, 0, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [121]:
## your code
def sample(x, c):
    assert len(x) > 0
    s = np.sum(x)
    x_sum = np.cumsum(x)
    val = np.random.random(c)*s
    #val = [38,56,32,29,34]
    x_sum[x_sum < val]
    res = list(np.searchsorted(x_sum, val))
    
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 0, 0]